#############################################################################
# Makefile for building: labSharedMemory.app/Contents/MacOS/labSharedMemory
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  labSharedMemory.pro
# Template: app
# Command: /Users/v144/Qt/5.5/clang_64/bin/qmake -o Makefile labSharedMemory.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt/5.5/clang_64/mkspecs/macx-clang -F/Users/v144/Qt/5.5/clang_64/lib
QMAKE         = /Users/v144/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = labSharedMemory1.0.0
DISTDIR = /Users/v144/Documents/workspace/C++/labSharedMemory/.tmp/labSharedMemory1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11 -Wl,-rpath,/Users/v144/Qt/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/v144/Qt/5.5/clang_64/lib -framework QtMultimediaWidgets -framework QtMultimedia -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		single_application.cpp \
		video_player.cpp moc_single_application.cpp \
		moc_video_player.cpp
OBJECTS       = main.o \
		single_application.o \
		video_player.o \
		moc_single_application.o \
		moc_video_player.o
DIST          = ../../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		labSharedMemory.pro single_application.h \
		video_player.h main.cpp \
		single_application.cpp \
		video_player.cpp
QMAKE_TARGET  = labSharedMemory
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = labSharedMemory.app/Contents/MacOS/labSharedMemory

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-mmacosx-version-min=10.11 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d labSharedMemory.app/Contents/MacOS/ || mkdir -p labSharedMemory.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: labSharedMemory.pro ../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		labSharedMemory.pro \
		/Users/v144/Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl \
		/Users/v144/Qt/5.5/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		/Users/v144/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/v144/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/v144/Qt/5.5/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/v144/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile labSharedMemory.pro
../../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.5/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/uic.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/lex.prf:
labSharedMemory.pro:
/Users/v144/Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl:
/Users/v144/Qt/5.5/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
/Users/v144/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/v144/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/v144/Qt/5.5/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/v144/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile labSharedMemory.pro

qmake_all: FORCE

labSharedMemory.app/Contents/PkgInfo: 
	@test -d labSharedMemory.app/Contents || mkdir -p labSharedMemory.app/Contents
	@$(DEL_FILE) labSharedMemory.app/Contents/PkgInfo
	@echo "APPL????" > labSharedMemory.app/Contents/PkgInfo
labSharedMemory.app/Contents/Resources/empty.lproj: 
	@test -d labSharedMemory.app/Contents/Resources || mkdir -p labSharedMemory.app/Contents/Resources
	@touch labSharedMemory.app/Contents/Resources/empty.lproj
	
labSharedMemory.app/Contents/Info.plist: 
	@test -d labSharedMemory.app/Contents || mkdir -p labSharedMemory.app/Contents
	@$(DEL_FILE) labSharedMemory.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,labCpp.labSharedMemory,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,labSharedMemory,g" -e "s,@TYPEINFO@,????,g" ../../../../Qt/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >labSharedMemory.app/Contents/Info.plist

all: Makefile \
		labSharedMemory.app/Contents/PkgInfo \
		labSharedMemory.app/Contents/Resources/empty.lproj \
		labSharedMemory.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents single_application.h video_player.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp single_application.cpp video_player.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r labSharedMemory.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_single_application.cpp moc_video_player.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_single_application.cpp moc_video_player.cpp
moc_single_application.cpp: ../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QSharedMemory \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qsharedmemory.h \
		../../../../Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../../Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		video_player.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers/QVideoWidget \
		../../../../Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers/qvideowidget.h \
		single_application.h
	/Users/v144/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/v144/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/v144/Documents/workspace/C++/labSharedMemory -I/Users/v144/Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/v144/Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers -I/Users/v144/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/v144/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/v144/Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/v144/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/v144/Qt/5.5/clang_64/lib single_application.h -o moc_single_application.cpp

moc_video_player.cpp: ../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers/QVideoWidget \
		../../../../Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers/qvideowidget.h \
		../../../../Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../../Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		video_player.h
	/Users/v144/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/v144/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/v144/Documents/workspace/C++/labSharedMemory -I/Users/v144/Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/v144/Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers -I/Users/v144/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/v144/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/v144/Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/v144/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/v144/Qt/5.5/clang_64/lib video_player.h -o moc_video_player.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		single_application.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QSharedMemory \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qsharedmemory.h \
		../../../../Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../../Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		video_player.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers/QVideoWidget \
		../../../../Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers/qvideowidget.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

single_application.o: single_application.cpp single_application.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QSharedMemory \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qsharedmemory.h \
		../../../../Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../../Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		video_player.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers/QVideoWidget \
		../../../../Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers/qvideowidget.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o single_application.o single_application.cpp

video_player.o: video_player.cpp video_player.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers/QVideoWidget \
		../../../../Qt/5.5/clang_64/lib/QtMultimediaWidgets.framework/Headers/qvideowidget.h \
		../../../../Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../../Qt/5.5/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video_player.o video_player.cpp

moc_single_application.o: moc_single_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_single_application.o moc_single_application.cpp

moc_video_player.o: moc_video_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_video_player.o moc_video_player.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

